Added the metadata schema as a standalone file
DARPA-ASKEM/Model-Representations pull request #10
Opened 2023-04-28 01:19 UTC by enoriega

Starting from the `extractions` branch, updated the metadata schema to reflect the [ER model designed in the Miro board](https://miro.com/app/board/uXjVMZvPN6o=/) and implemented in the [GitHub repository](https://github.com/ml4ai/ASKEM-TA1-DataModel).

The metadata schema is automatically exported from Pydantic, and it is substantial, so I factored it out into its own file (`metadata_schema.json`). This will allow us to drop in a replacement if the ER model changes with minimal modifications to the rest of the code in this repository.  This also generalizes the metadata beyond petri-nets to any abstract representation of the model.

We updated the test data file `sir.json` to add a metadata entry compliant with the schema and updated the validator code to be aware of the new schema file.

2023-04-28 01:57 UTC, brandomr commented
@enoriega thanks for putting this together! I'll give it a review ASAP. @Tranway1 can you take a look as well and make sure this works for you? I assume it should since you and @enoriega already worked out the shared schema between your respective groups.

@enoriega could you point me to the pydantic? That's actually much easier to read so will help get me oriented 😄

2023-04-28 02:00 UTC, enoriega commented
@brandomr Yes, you can find it at https://github.com/ml4ai/ASKEM-TA1-DataModel
The README has the intended use cases and you can see the data classes within the `data_model` subdirectory.

2023-04-28 02:02 UTC, enoriega commented
BTW, @Tranway1 and I are working on a new branch https://github.com/ml4ai/ASKEM-TA1-DataModel/tree/provenance
We will likely merge it into main tomorrow and the changes here reflect the update in this branch

2023-04-28 15:39 UTC, Tranway1 commented
> 

The changes work for our side.

2023-05-01 18:36 UTC, mattprintz requested changes
@enoriega A couple things from my pass through:

1. The schema itself looks good, however in the representation, `variable_statements` is required to exist, and I think that all metadata, including these, should be optional. That is, we should be able to be run through tools without errors (but possibly with some optional enhancements that aren't used).
2. I'm not sure if it makes sense to include the full representation of the model in to the metadata file. Perhaps it should be limited to only the subset of data?

I threw together a quick branch with some fixes for the above. Feel free to merge in my branch (or I could create a PR to merge it to your branch if that's easier. Or you can ignore my changes and implement your own.

https://github.com/DARPA-ASKEM/Model-Representations/compare/metadata-schema...mp/metadata-schema?expand=1

2023-05-02 02:46 UTC, brandomr commented
@enoriega @Tranway1 this looks great! 

I do agree with @mattprintz on his points. Generally this should be flexible since we'll want to be able to store certain things that have differing metadata but if it comes from your system we can expect this spec. Since the `metadata` is attached to the model we shouldn't have to include the model itself.

@enoriega @Tranway1 can you explain a bit how `columns` and `dataset` relate? I was surprised that `columns` are the outer key--I don't think it actually matters but am curious about this.

I'm also curious whether there will be annotations/extractions that aren't explicitly related to `variables`. Since the metadata spec is very focused on `variables` I take it the answer is no or at least not for the time being?

2023-05-02 03:49 UTC, Tranway1 commented
> 

@brandomr We now have a 1-to-N relation between variable and dataset columns. For each variable X, we associate X with several columns which belong to specific dataset as you can tell from column id consisting of "datasetID-columnIndex".  We can also use dataset id as the outer key if needed.

2023-05-03 00:32 UTC, enoriega commented
@mattprintz @brandomr (cc. @Tranway1 ) We can certainly make `variable_statements` optional. And in that case, any metadata element too. I will update the PR with this change

I also agree with removing the model from the metadata. In fact it was there because of my ignorance about how does working with json schema work. Upon reviewing the suggested PR, I understood the point

2023-05-04 13:20 UTC, merged