InterTypes-generated python interface for decapodes.
DARPA-ASKEM/Model-Representations pull request #64
Opened 2023-11-01 13:36 UTC by olynch

This adds the python files, as well as the original intertype file that was used to generated them.

2023-11-03 02:25 UTC, fivegrant submitted a review, later dismissed
Looks good overall!

However, it looks like there's some missing metadata we're expecting as [provided by SyntacticModels](https://algebraicjulia.github.io/SyntacticModels.jl/dev/generated/decapodes_examples/).

I think @p-stokes also added annotations which we'll probably need along with the header.

2023-11-03 02:25 UTC, fivegrant commented on decapodes/decapodes.it
> +end
```suggestion
end

struct Header
    id::Union{String, Nothing}
    description::String,
    name::String,
    model_version::String,
    schema::String
    schema_name::String	
end

struct ASKEMDecapode
  header::Header
  model::DecaExpr
end
```

2023-11-03 02:25 UTC, fivegrant commented on decapodes/decapodes.it
> +end
Note: Not sure if InterTypes can handle Unions.

2023-11-03 02:25 UTC, fivegrant commented on decapodes/decapodes.it
> +end
Didn't include annotations in the above. They should probably be there.

2023-11-29 17:06 UTC, jpfairbanks commented
@olynch, do we need to update this since there has been changes to InterTypes?

2023-11-29 17:12 UTC, jpfairbanks commented on decapodes/decapodes.it
> +end
@olynch it looks like we to add the following from the SyntacticModels codebase:

```julia
@sum ASKEMDeca begin
  ASKEMDecaExpr(header::Header, model::Decapodes.DecaExpr, annotations::Vector{Annotation{Symbol,Symbol}})
  ASKEMDecapode(header::Header, model::Decapodes.SummationDecapode, annotations::Vector{Annotation{Symbol,Symbol}})
end
```

2024-01-03 21:27 UTC, olynch commented
Updated with latest intertypes/decapodes file.

2024-01-06 15:09 UTC, jpfairbanks requested changes
@olynch, it looks like we are still missing the SyntacticModels part. 

https://github.com/AlgebraicJulia/SyntacticModels.jl/blob/0ea6f64fffd6b28824a99d028f5b65d3a0cad4f1/src/decapodes.jl#L12

which depends on https://github.com/AlgebraicJulia/SyntacticModels.jl/blob/0ea6f64fffd6b28824a99d028f5b65d3a0cad4f1/src/amr.jl#L81

2024-01-18 04:06 UTC, olynch commented
Freshly generated intertype modules from [DiagrammaticEquations](https://github.com/AlgebraicJulia/DiagrammaticEquations.jl) and [SyntacticModels](https://github.com/AlgebraicJulia/SyntacticModels.jl/).

2024-01-23 01:01 UTC, jpfairbanks approved these changes

2024-01-24 05:29 UTC, merged